### ISSUE TITLE
tests work in devtools::test() but fail in devtools::check()

### ISSUE THREAD

**Issue by bbolker** [bbolker/broom.mixed#10]
don't know what's going on. `devtools::test(".")` works fine (except for expected warnings) in a clean session, but `devtools::check(".")`

I suspect it has to do with the fact that some of the same S3 generics defined in both broom and broom.mixed, but I'm pretty mystified. Weakened the dependency on `broom` (only importing some stuff now), which is probably a good idea in any case, but doesn't seem to fix it.

Not everything fails, just these:

> OK: 29 SKIPPED: 1 FAILED: 6
> 1. Failure: tidy works on lme4 fits (@test-lme4.R#15) 
> 2. Failure: tidy works on lme4 fits (@test-lme4.R#16) 
> 3. Failure: tidy works with more than one RE grouping variable (@test-lme4.R#41) 
> 4. Error: ran_modes works (@test-lme4.R#79) 
> 5. Failure: tidy works on nlme/lme fits (@test-nlme.R#14) 
> 6. Failure: Fit without data in returned structure works when data are given (@test-nlme.R#80)

**Comment by bbolker** [comment]
OK, after poking around in the test directory, it's clear that this *is* happening because the generics in `broom` rather than `broom.mixed` are getting found.  Ugh ... Not sure how to fix this ...

**Comment by dgrtwo** [comment]
Anything I can do from the broom side to fix this? (I haven't been involved but great work on this package so far)

**Comment by bbolker** [comment]
Got this working by hacking the tests a little bit. That's worrisome, but on the other hand all the tests work just fine when run via `test(.)`, so I believe everything will work fine in any normal environment. (I've never understood exactly what magical environment `check(.)` runs in: I've had lots of headaches in the past from things that worked fine in a clean batch or interactive environment but not in `check(.)`.

Ideally, `broom.mixed`'s S3 generics will mask everything in `broom`, so we can develop `broom.mixed` without worrying about deprecating the broom versions for a while.

**Comment by bbolker** [comment]
@dgrtwo , slightly off-topic, but the most helpful things for me would be

(1) close out the various issues I've commented on
(2) accept [this minor pull request](https://github.com/tidyverse/broom/pull/269)

FWIW the travis checks on that PR failed because

> The job exceeded the maximum time limit for jobs, and has been terminated.

See my ruminations [here](https://github.com/bbolker/broom.mixed/issues/9)
