### ISSUE TITLE
refactoring to remove `plyr` + `reshape2` dependence using `dplyr` + `tidyr`

### ISSUE THREAD

**Issue by IndrajeetPatil** [bbolker/broom.mixed#102]
The `broom` package was refactored a while ago to do this (since these two packages are not under active development anymore in favor of `tidyr`) and maybe the same can be done with `broom.mixed`.

This might be a beginner-friendly issue if someone wants to contribute a PR.

**Comment by bbolker** [comment]
this seems like a reasonable idea (although in my old-fashioned way I'm almost *more* comfortable with "Hadleyverse 1" (plyr/reshape2) than with tidyverse because it's **not** under such rapid development ...)  I don't know if I call it "refactoring" since I doubt that much structural change has to happen - it would mostly be a matter of digging through the code base and replacing plyr/reshape2 idioms with tidyverse equivalents

**Comment by vincentarelbundock** [comment]
I removed the two packages in question in this PR: https://github.com/bbolker/broom.mixed/pull/104

**Comment by vincentarelbundock** [comment]
I would also like to propose a second round of dependency removal.

My motivation is that I would like to import `broom.mixed` by default in my [modelsummary package](http://vincentarelbundock.github.io/modelsummary) but I am wary of pulling in all those upstream dependencies.

I propose:

1. Swapping `broom` for `generics`, as is now recommended by the `broom` team (will need to look into `broom::augment_columns` calls and a few others).
2. Move `TMB`, `nlme`, and `coda` to Suggests.
3. Include assertion checks with informative error messages in case those packages are not available and the method is called (In principle, the `TMB`/`nlme` methods should only be invoked when users operate on objects produced by those packages, so they should be available. But one corner case would be loading an object from RDS on a machine where the package is not installed).

The assertion function could look like this (it would not be exported and would be set to `@keywords internal`):

```
assert_dependency <- function(library_name) {
  if (!requireNamespace(library_name, quietly = TRUE)) {
    stop(sprintf("Please install the %s package.", library_name))
  }
}
```

**Comment by vincentarelbundock** [comment]
@IndrajeetPatil thanks for the suggestion! I think you can close this now that both of my PRs have been merged. Master has 4 fewer dependencies than CRAN.

**Comment by IndrajeetPatil** [comment]
This is awesome!! 

The original reason for why I had opened this issue was indeed to reduce the no. of dependencies since I also rely on `broom.mixed` in my packages, but it felt too selfish of me to articulate it that way ;)

Thanks a lot for your work and for Ben to being open to this.
