### ISSUE TITLE
augment fails for class gamlss when the newdata argument is used

### ISSUE THREAD

**Issue by buyske** [bbolker/broom.mixed#109]
For a `gamlss` object, augment uses `augment.glm`, which in turn calls `predict(x, newdata, type = type.predict)`.
However, `gamlss:::predict.gamlss` has a second argument of `what`, not `newdata`, so the result is
    Error in match.arg(what) : 'arg' must be NULL or a character vector

Here's an example:
```
data(abdom, package="gamlss.data")
gamlss1 <- gamlss(
   y ~ pb(x),
   sigma.fo = ~ pb(x),
   family = BCT,
   data = abdom,
   method = mixed(1, 20)
   )
augment(gamlss1, newdata = abdom)
```

Sorry to leave this an issue, not a pull request, but I am getting tangled up with methods and namespaces.

**Comment by bbolker** [comment]
On closer inspection it seems as though `gamlss` models may not really belong in `broom.mixed` at all (there are tidiers for `gamlss` fits in `broom` as well), in which case I'll probably remove these methods form here. For what it's worth, your example seems to work fine with `broom::augment()` ...

**Comment by bbolker** [comment]
It turns out that `gamlss` tidiers *are* staying in broom.mixed. However, this seems to work with the current version of gamlss (5.3.4)  + devel broom.mixed ?

**Comment by bbolker** [comment]
closing this, happy to re-open if warranted
