### ISSUE TITLE
update contributor list

### ISSUE THREAD

**Issue by bbolker** [bbolker/broom.mixed#11]
Not sure which of the people in broom's `DESCRIPTION` file are contributors specifically to the mixed-model stuff. Definitely David Robinson, Ben Bolker, Will Petry, Dieter Menne (@dmenne), Josh Wiley, Paul-Christian Buerkner, Benjamin Nutter, Chris Hua (@stillmatic), Jonah Gabry (@jgabry) ...

```
***  brms_tidiers.R
author dgrtwo
author Paul-Christian Bürkner
***  gamlss_tidiers.R
author dgrtwo
***  lme4_tidiers.R
author bbolker
author Benjamin
author dgrtwo
author Patrick Kennedy
***  mcmc_tidiers.R
author bbolker
author Dave Robinson
author dgrtwo
author jgabry
***  nlme_tidiers.R
author Benjamin
author Chris Hua
author Dieter Menne
***  rstanarm_tidiers.R
author dgrtwo
author jgabry
```

**Comment by bbolker** [comment]
confirmed:

- Paul Buerkner
- Jonah Sol Gabry
- Dieter Menne

(no: Benjamin Nutter)

**Comment by pkq** [comment]
Thanks for the offer, and apologies for the delayed response. I'd be honored to be listed, although I see that you've closed the issue, and given how little I actually contributed, won't be offended if you end up leaving me off. Thanks for thinking of me, and for the fantastic package!
