### ISSUE TITLE
Support for nlme::varFunc classes

### ISSUE THREAD

**Issue by billdenney** [bbolker/broom.mixed#114]
Would there be interest in a PR for the nlme::varFunc classes?

My use case is that I'm generating a model with `weights=varExp(form=~fitted(.)|covariate1*covariate2)`.  The fact that the `varExp()` coefficients are missing from `tidy(my_model)` means that I need to work out a different way to get those variance coefficients into the `tidy()` table.

I would think that the simplest way to add the coefficients would be to make a new `tidy.varExp()` (and for all the other `varFunc` classes) where the results of that tidy would be added to the `tidy()` tibble with a `bind_rows()` call.

Does that seem useful to you and like the right way to go with the PR?

**Comment by billdenney** [comment]
Here is what I ended up writing that worked for my current example:

```r
tidy.varExp <- function(x, ...) {
  term_name <-
    sprintf(
      "var_%s(%s)",
      class(x)[1],
      as.character(as.formula(x))[[2]]
    )
  tibble(
    effect="residual",
    group=names(coef(x)),
    term=term_name,
    estimate=coef(x),
    std.error=NA_real_,
    df=NA_real_,
    statistic=NA_real_,
    p.value=NA_real_
  )
}
```

**Comment by bbolker** [comment]
I would certainly be happy with a PR. More broadly, the sensible way (I think) to incorporate this in `tidy.lme` would be to add option(s) to the "effects" argument ("weights", "correlation"? "var_model", "cor_model"? "het_pars", "cor_pars"?)

**Comment by billdenney** [comment]
That makes sense to implement it similar to how `"ran_pars"` is implemented, and I like the name "var_model".  As there will be many flavors of the effects to implement, I was going to put it in its own function (or set of functions), and that's why I was suggesting that it gets its own `tidy()` S3 method.  I think that the code would start looking very nested-if-block heavy to handle all the varFunc classes without each having its own `tidy()` S3 method, and it shouldn't cause a collision since the varFunc classes are distributed with base R.  (So, anyone who names their class "varExp" already likely has some headaches.)

**Comment by bbolker** [comment]
putting them in their own set of functions seems like a good first step/way to integrate this into the overarching `tidy.lme` function.
