### ISSUE TITLE
Feature Request: Add estimated=FALSE for fixed sigma in nlme package models

### ISSUE THREAD

**Issue by billdenney** [bbolker/broom.mixed#116]
The nlme package supports fixed sigma values.  Similar to the updates made in #115 for fixed varFunc parameters, a similar "estimated" column should be added and set to `FALSE` when the sigma is fixed.

It was not added within #115 because I couldn't readily see where the information that sigma is fixed is stored in the model object (other than the call).

**Comment by bbolker** [comment]
Here you go ...

```
library(nlme)
m1 <- lme(distance ~ age, random = ~age |Subject, data = Orthodont)
m2 <- update(m1, control = lmeControl(sigma = 1))
waldo::compare(m1,m2)
m12 <- list(m1,m2)
sapply(m12, function(x) attr(x$modelStruct, 'fixedSigma'))
sapply(m12, function(x) "lSigma" %in% rownames(x$apVar))
```
```

**Comment by billdenney** [comment]
Well, that's really cool.  Thanks!  On it...

I will put this into #115, so don't merge quite yet.

**Comment by bbolker** [comment]
In case it's not obvious, I think the first test (attribute of modelStruct) is much better to use than the second (absence of "lSigma" in apVar names)

**Comment by billdenney** [comment]
I just implemented that, and it works.  PR in 5... 4...
