### ISSUE TITLE
unable to load shared object 'TMB.so'

### ISSUE THREAD

**Issue by hsinhungh** [bbolker/broom.mixed#121]
I installed broom.mixed package via conda ```conda install -c conda-forge r-broom.mixed```, however, it doesn't import and shows error message:
```
library(broom.mixed)

Error: package or namespace load failed for ‘broom.mixed’:
 .onLoad failed in loadNamespace() for 'TMB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/local/home/hsinhung/anaconda3/envs/r-env/lib/R/library/TMB/libs/TMB.so':
  libopenblas.so.0: cannot open shared object file: No such file or directory
```
Any suggestion how I can get this package going in Anaconda jupyter notebook?  Thanks!

**Comment by bbolker** [comment]
Hmm, I have no idea at all about conda. broom.mixed doesn't even have a strong dependency on TMB (it "Suggests" rather than "Imports" TMB). Do you know how to contact the person who is in charge of building/packaging the broom.mixed package for conda ... ?

**Comment by jmuhlenkamp** [comment]
Hi @hsinhungh, I briefly tried to replicate the error with a simple conda env and was unable to (see my .yml config below).  If you are able to create a reprex for this (see https://www.tidyverse.org/help/#reprex), we may be able to help.

Here is a small conda env that works fine without errors for me on a Mac

```
name: broom
channels:
  - anaconda
  - r
  - conda-forge
dependencies:
  - r-base=3.6.1
  - r-broom.mixed
```

**Comment by hsinhungh** [comment]
I tried ```reprex``` but it "expectedly" doesn't work with jupyter notebook.

I created a clean R environment in Anaconda via below commands:

```conda create -n r_env_test r-essentials r-base``` (following [Anaconda R env instruction](https://docs.anaconda.com/anaconda/user-guide/tasks/using-r-language/#creating-a-new-environment-with-r))
```conda activate r_env_test```
```conda install -c conda-forge r-broom.mixed``` (following [Anaconda broom.mixed instruction](https://anaconda.org/conda-forge/r-broom.mixed))

then I enter ```R``` console, and execute ```library(broom.mixed)```.  The error pops up right away:

```
> library(broom.mixed)
Error: package or namespace load failed for ‘broom.mixed’:
 .onLoad failed in loadNamespace() for 'TMB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/local/home/hsinhung/anaconda3/envs/r_env_test/lib/R/library/TMB/libs/TMB.so':
  libopenblas.so.0: cannot open shared object file: No such file or directory
In addition: Warning message:
package ‘broom.mixed’ was built under R version 3.6.3
```

Thanks so much for your support.  I hope the way I reproduce the error help with your investigation.

**Comment by bbolker** [comment]
I'm sorry, but I really can't help very much, I never use conda at all. Have you tried installing and loading the TMB package to see if you get the same error? https://anaconda.org/conda-forge/r-tmb

**Comment by jmuhlenkamp** [comment]
Does the object in question exist?

```
# assuming Linux or Mac
ls -al /local/home/hsinhung/anaconda3/envs/r_env_test/lib/R/library/TMB/libs/TMB.so
```

Also, what operating system are you on?  I'm unable to replicate the error on either Mac or Linux so doubt I can be of much help...

If you're still stuck, you might be able to get help in the R4DS Slack community (see Slack at top here: https://www.rfordatasci.com)

**Comment by hsinhungh** [comment]
Thanks very much for your support and sorry for occupying your precious time.  I was lucky to also get some support from Stackoverflow community https://stackoverflow.com/questions/70727524/unable-to-load-shared-object-tmb-so.  It turned out that "Anaconda" and "Conda Forge" package channels can sometimes be incompatible and leading to issues in library management.  As a normal user who just want to get some analysis done, I am so frustrated in spending days in learning "undocumented" technical issues like this.  Guess it is what it is.  :(
Thanks so much for all your support!
