### ISSUE TITLE
feature request: methods for mediate.mer class

### ISSUE THREAD

**Issue by corybrunson** [bbolker/broom.mixed#124]
The broom package provides methods for objects of class 'mediate' produced by `mediation::mediate()`, but not for objects of class 'mediate.mer' produced by the same function when the inputs are mixed effects models. broom.mixed seems like the natural home for such methods.

If there is interest, i would be glad to draft methods, adapting code from `broom:::tidy.mediate()` and from `broom.mixed:::tidy.merMod()` as appropriate and following conventions.

**Comment by bbolker** [comment]
Sure!
