### ISSUE TITLE
Error calling library

### ISSUE THREAD

**Issue by fcorowe** [bbolker/broom.mixed#128]
Hi, 

All seems to work fine when I install `broom.mixed`, but R returns the error below when I run `library(broom.mixed)`. It means I can't use `broom.mixed`.

```
Error: package or namespace load failed for ‘broom.mixed’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘globals’
```
Any ideas how I can resolve this issue? 

I can see the `broom.mixed` folder in the `library` folder in my machine. 

Thanks

**Comment by bbolker** [comment]
What happens if you `install.packages("globals")` first?

**Comment by bbolker** [comment]
Closed unless/until there is more to work with. (Happy to re-open.)
