### ISSUE TITLE
Generate test data

### ISSUE THREAD

**Issue by dmenne** [bbolker/broom.mixed#13]
For testing Stan/brms-based functions on CRAN, prepared data are required to avoid long compile times. Currently (including my PR), there is a `run_examples.R` file in `inst/extdata` to generate  rds-files.

I suggest to follow @paul-buerkner 's `brms` package to make sure these files are updated for releases:

- rename `run_examples.R` to `generate_test_data.R` and put these into `./tests`
- It will be run on normal tests - maybe provide some environment to avoid running it in your daily work
- Add `generate_test_data.R` to `.Rbuildignore` to avoid running it on CRAN

If ok, I will submit a PR

**Comment by bbolker** [comment]
I would prefer to go the other way (as in brms/re-building all the examples less often). lme4 looks for an `LME4_TEST_LEVEL` environment variable (defaults to 1, I think), only does expensive stuff if the value is >1 (in principle there could be lots of levels, but I don't think we ever got beyond 1 vs 2 ...)

**Comment by dmenne** [comment]
I checked the lme4 solution, and I am not so happy about it. It is good when you have short, a bit longer, and a bit more longer tests, but when brms/stan comes into play we have short, bit longer, and glacial methods. 
Since this package is about extracting coefs from results, we should not wait minutes till brms/stan has recompiled, but rather use the results in the cache/package to test the coefficent ordering.

**Comment by paul-buerkner** [comment]
With regard to brms, we can always use the most up to date cached models via

```R
fit_brms1 <- brms:::rename_pars(brms:::brmsfit_example1)
# same with other example models
```

(see also https://github.com/paul-buerkner/brms/blob/master/tests/testthat/tests.brmsfit-methods.R).

In this case, we don't even need to store the models inside broom.mixed.

**Comment by dmenne** [comment]
Agreed. That's why I prefer you method in this case (lme4 is somewhat different in proportions)

**Comment by bbolker** [comment]
OK, I'm confused about a few things.  I don't really object to *any* solution as long as 

- it's reasonably clear/explicit/straightforward
- it allows us to regenerate examples **only when we specify** (at first glance I don't see why `brms` doesn't do the regeneration on any `R CMD check` ... aren't all .R files in `tests` run by default?)
- probably best if the examples are non-monolithic (i.e. separate generating files for each package, so that they can e.g. be run in parallel by `make -j ...`, and example output stored in separate `rda` or `rds` files
    - from this perspective an exact copy of the `brms` protocol (`devtools::use_data(...,internal=TRUE`, overwrite=TRUE)` would be problematic because (if I understand correctly) we'd always have to store all the examples in a single go ...?
- what I meant to suggest for copying `lme4` was that the *regeneration of examples* would only be triggered if the `BM_TEST_LEVEL` variable was set to a value >1 ... although since we would be doing this fairly rarely, also probably fine to simply do it manually when we so choose

**Comment by dmenne** [comment]
- "it allows us to regenerate examples" etc: That's a point I also don't understand, because it runs every time in my play version. Maybe Paul can explain the trick.
 - I see good points  @bbolker's "separate output files" instead of a common one, even if it is package only. As a user, I often start from prepared examples outputs with rstan/brms
- Maybe I did not understand the lme4 mechanism correctly. Assume you want to test an coefficient extraction on a model that runs very long - is there an automatic way to say "run extraction only?"

**Comment by paul-buerkner** [comment]
I have no idea why it doesn't run automatically for me or on CRAN... But why not just move it outside of /tests to avoid rerunning it on your machines as well?

**Comment by bbolker** [comment]
if you `.Rbuildignore` and always test by building the tarball and then testing the tarball (as recommended), then it wouldn't get run.  I sometimes get sloppy and run `R CMD check` in the directory, so I would prefer to leave the generating .R file out of /tests ...

**Comment by dmenne** [comment]
brms_fit_examples  is not in .Rbuildignore, so I am surprised that Uwe does not mind the long run time. Anyway, there is a test/local in brms, so something like that would work

**Comment by paul-buerkner** [comment]
It is in .Rbuildignore: See https://github.com/paul-buerkner/brms/blob/master/.Rbuildignore

**Comment by dmenne** [comment]
https://github.com/paul-buerkner/brms/commit/052525fedc663fa7cb5d25a0f1725cfd2b2415fd#diff-bc92b187c74649b3e0a039784ff93b39

But only since 5 minutes ._) Never mind, I just tried to understand.

**Comment by paul-buerkner** [comment]
A year (we have 2018 now) ;-)

**Comment by dmenne** [comment]
Too bad .)....

**Comment by dmenne** [comment]
Another directory...

https://stackoverflow.com/questions/32328802/where-to-put-data-for-automated-tests-with-testthat

There was a comment by a guy called Ben Bolker to use `/inst/testdata`. Sound Ok from a R-core viewpoint, but I hate the confusing it causes when things are shifted up a level on install; you never know which version is being used.

**Comment by bbolker** [comment]
this seems to work OK now; closing.
