### ISSUE TITLE
Error in `tidy.glmmTMB(conf.int = TRUE)` with `glmmTMB(family="tweedie")`

### ISSUE THREAD

**Issue by ddsjoberg** [bbolker/broom.mixed#135]
Hello! Thanks for this wonderful tool!

A {gtsummary} user posted about this error, and I am reporting here https://github.com/ddsjoberg/gtsummary/issues/1368

The tidier for the `'glmmTMB'` class has an error when the family is `'tweedie'` and we request the confidence interval.

Example below! Thank you!

``` r
library(glmmTMB)

# THIS WORKS
m1 <- glmmTMB(count ~ mined + (1|site), family="gaussian", data=Salamanders)
broom.mixed::tidy(m1, conf.int = TRUE)
#> # A tibble: 4 × 10
#>   effect   compo…¹ group term  estim…² std.e…³ stati…⁴   p.value conf.…⁵ conf.…⁶
#>   <chr>    <chr>   <chr> <chr>   <dbl>   <dbl>   <dbl>     <dbl>   <dbl>   <dbl>
#> 1 fixed    cond    <NA>  (Int…   0.295   0.177    1.67  9.52e- 2 -0.0516   0.643
#> 2 fixed    cond    <NA>  mine…   1.97    0.245    8.03  9.45e-16  1.49     2.45 
#> 3 ran_pars cond    site  sd__…   0.370  NA       NA    NA         0.177    0.770
#> 4 ran_pars cond    Resi… sd__…   2.41   NA       NA    NA         0.177    0.770
#> # … with abbreviated variable names ¹​component, ²​estimate, ³​std.error,
#> #   ⁴​statistic, ⁵​conf.low, ⁶​conf.high

# BUT THE tweedie FAMILY DOES NOT WORK
m2 <- glmmTMB(count ~ mined + (1|site), family="tweedie", data=Salamanders)
broom.mixed::tidy(m2, conf.int = TRUE)
#> Error in dimnames(x) <- dn: length of 'dimnames' [1] not equal to array extent
```

<sup>Created on 2022-10-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bbolker** [comment]
This is en route to being fixed in the development version of glmmTMB. https://github.com/glmmTMB/glmmTMB/pull/871

See if 

```r
remotes::install_github("glmmTMB/glmmTMB/glmmTMB@rename_thetaf")
```
resolves the problem?

**Comment by ddsjoberg** [comment]
Thanks @bbolker !! You're correct, using the specified branch fixes the issue!

**Comment by nalimilan** [comment]
It works! Thanks everyone!

**Comment by nalimilan** [comment]
I just noticed that the same (or a similar) problem happens with `diagnose`, even with glmmTMB 1.1.5. With the reproducer in the OP, `diagnose(m1)` works, but `diagnose(m2)` gives an error:
```R
> diagnose(m2)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

Thanks again.

**Comment by nalimilan** [comment]
Thanks, it works!
