### ISSUE TITLE
tidy() fails for rstanarm

### ISSUE THREAD

**Issue by druedin** [bbolker/broom.mixed#153]
I'm ultimately trying to figure out why the pool() function in package mice no longer works with rstanarm.

The tidy() function in broom.mixed seems to fail for some stanreg objects. Example (from [R/rstanarm_tidiers.R](https://github.com/bbolker/broom.mixed/blob/HEAD/R/rstanarm_tidiers.R)):

```
library(rstanarm)
library(broom.mixed)
fit = stan_glmer(mpg ~ wt + (1|cyl) + (1+wt|gear), data = mtcars, iter = 300, chains = 2)
# non-varying ("population") parameters
tidy(fit, conf.int = TRUE, prob = 0.5)                              ## FAILS
```

We get: Error in check_dots(...) : unknown arguments: prob

The following works:
```
tidy(fit, effects = "ran_pars")                                         ## WORKS
tidy(fit, effects = "fixed")                                            ## also works
```

**Comment by bbolker** [comment]
what is `prob` supposed to be doing in this example?  As far as I can see in `broom.mixed:::tidy.stanreg`, there is no explicit `prob` argument and the `...` argument doesn't get used anywhere (it's needed for S3 method compatibility), so even if we didn't throw an error, the `prob` argument would be silently ignored.  Do you mean `conf.level` (which gets passed as the `prob` argument of `rstanarm::posterior()` ?)  Can you post an example of the use of `pool()` failing?

**Comment by druedin** [comment]
Not sure. Here's an example with the pool() function.

This works as expected:
```
library(mice)
data(nhanes)
imp = mice(nhanes, m = 3, print = FALSE)
mod = with(imp, lm(age ~ bmi + chl))
summary(pool(mod))
```

This one does not:
```
library(rstanarm)
ms = with(imp, stan_glm(age ~ bmi + chl))
library("broom.mixed")
summary(pool(ms))
```

Yields "Error in check_dots(...) : unknown arguments: parametric" as reported for the example included in the rstanarm_tidiers.

**Comment by bbolker** [comment]
Did this work in previous versions (you do say "no longer works")?  

The `parametric` argument has been around in `mice` [for about 4 years](https://github.com/amices/mice/commit/14ad2e16d9953a5e5cbe7801ab8224546f252d60) and the `check_dots()` test has been in `tidy.stanreg` [for two years](https://github.com/bbolker/broom.mixed/commit/9601528d7a9cdcec1ad8b23365ccd2b4670fcfe5). 

It would be easy enough to add `.ignore = "parametric"` to the `check_dots()` call, if that seems warranted, but I don't want to overlook something else being wonky ...

**Comment by druedin** [comment]
Yes, it's ultimately from my teaching material, so this approach definitely worked. I also found it in online tutorials, when I tried to figure out why this no longer works. I could reduce it as far as this.

**Comment by bbolker** [comment]
Would it be reasonable to assume that this broke two years ago but that we haven't noticed until now? Looking at the machinery, it seems as though other tidying methods are probably just silently ignoring the `parametric` argument ... e.g. `broom:::tidy.lm` accepts `...` without complaining, but doesn't pass it on to any other functions ...

**Comment by druedin** [comment]
I have last used the my code in February 2024, but I cannot rule out entirely that the machine I used then had outdated packages (admin do not routinely update R). I'm afraid this isn't helpful.
