### ISSUE TITLE
library 'lme4' not found

### ISSUE THREAD

**Issue by Navneet89** [bbolker/broom.mixed#18]
I am trying to run a mixed model using lmerTest for which I needed to install lme4 but R is not recognizing the package.

> install.packages("lme4")
Installing package into ‘C:/Users/nd911/OneDrive/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lme4_1.1-17.zip'
Content type 'application/zip' length 5229366 bytes (5.0 MB)
downloaded 5.0 MB

package ‘lme4’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘lme4’

The downloaded binary packages are in
	C:\Users\nd911\AppData\Local\Temp\Rtmp6bYGvh\downloaded_packages
> library(lme4)
Error in library(lme4) : there is no package called ‘lme4’

Here is a little more info about my session:
> options(repos="https://cran.rstudio.com")
> a1 <- available.packages()
> a1[a1[,"Package"]=="nlme",]
                               Package                                Version                               Priority                                Depends 
                                "nlme"                              "3.1-137"                          "recommended"                         "R (>= 3.4.0)" 
                               Imports                              LinkingTo                               Suggests                               Enhances 
     "graphics, stats, utils, lattice"                                     NA                          "Hmisc, MASS"                                     NA 
                               License                        License_is_FOSS                  License_restricts_use                                OS_type 
           "GPL (>= 2) | file LICENCE"                                     NA                                     NA                                     NA 
                                 Archs                                 MD5sum                       NeedsCompilation                                   File 
                                    NA                                     NA                                  "yes"                                     NA 
                            Repository 
"https://cran.rstudio.com/src/contrib" 
> sessionInfo()
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    yaml_2.1.14   
> R --vanilla
Error: object 'R' not found
> sessionInfo()  ## see if you have a *clean* session (your session above isn't clean, it has non-default
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.4.4  rsconnect_0.8.5 tools_3.4.4     yaml_2.1.14    
> ## packages loaded)
> packageVersion("nlme")
[1] ‘3.1.137’
> sapply(.libPaths(),packageVersion,pkg="nlme")  ## see if you have multiple versions installed
$`C:/Users/abc/OneDrive/Documents/R/win-library/3.4`
[1]   3   1 137

$`C:/Program Files/R/R-3.4.4/library`
[1]   3   1 131   1

> require("lme4")
Loading required package: lme4
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘lme4’

**Comment by GuiMarthe** [comment]
This seems like a problem with the `lme4` package. Not directly related to `broom.mixed`.
Did the errors begin after you installed `broom.mixed`?

**Comment by Navneet89** [comment]
I do not remember installing broom.mixed. My r was crashing so I decided to uninstall and reinstall. After reinstall, I have been getting this error with multiple packages such as lmerTest, ggcorrplot, stringr etc. The error looks like this:
_Error: package or namespace load failed for ‘stringr’ in inDL(x, as.logical(local), as.logical(now), ...):
 ICU init failed: U_FILE_ACCESS_ERROR_

> library(lmerTest)
Error: package or namespace load failed for ‘lmerTest’ in inDL(x, as.logical(local), as.logical(now), ...):
 ICU init failed: U_FILE_ACCESS_ERROR

**Comment by bbolker** [comment]
The reason people here are talking about broom.mixed is that you have posted to the broom.mixed issues list.

As you have pointed out in your last comment, this is not really specific to any mixed-model packages.  Googling this error message took me [here](https://stackoverflow.com/questions/38026485/icu-init-failed-u-file-access-error-when-running-swirl-in-r) and [here](https://github.com/gagolews/stringi/issues/170) and [here](https://stackoverflow.com/questions/48066341/u-file-access-error?noredirect=1&lq=1).

I would try reinstalling `stringi`.  If that doesn't work, you're going to have to go somewhere else to follow up (e.g. `r-help@r-project.org`) ...

  good luck.
