### ISSUE TITLE
Check for duplication of efforts in tidybayes package

### ISSUE THREAD

**Issue by alexpghayes** [bbolker/broom.mixed#22]
It looks like the Stan development community is working fairly closely with the [`tidybayes`](https://github.com/mjskay/tidybayes) developers. It seems like a conversation about what belongs in `broom.mixed` and what belongs in `tidybayes` would be valuable and could save you some time.

**Comment by bbolker** [comment]
OK.  Do you know if there's a straightforward way to invite @mjskay to this issue?

Sorry I missed the boat on July 2 submission of this package - I was close but got too busy/went to a conference.

**Comment by alexpghayes** [comment]
I think tagging like you have is all you need to do. You might also find the [discussion](http://discourse.mc-stan.org/t/unifying-names-of-output-columns-in-bayesplot-tidybayes-etc/4577/12) on the Stan discourse useful, which is what motivated this issue in the first place.

**Comment by mjskay** [comment]
Yes, tagging me works! :)

As for overlap, I wonder if there is something you can point me at to get a sense of what direction `broom.mixed` is planning to go? Looking at the the existing `tidy` function in this package, the current duplication may not be huge, though making sure column names are similar would be sensible. 

My sense is that the focus of `broom` is probably to make single functions that are succinct and generate by-default-useful things. `tidybayes` tends to be a little more verbose, with a focus on giving primitives for customized munging. The other difference I can see is that `tidybayes` separates the initial tidying process from the process of summarizing draws into points and intervals: all the basic tidying function in `tidybayes` return long-format data frames of draws. If point estimates are desired, a family of functions (`mean_qi`, `median_qi`, `mode_hdi`, etc) can generate them, or ggplot stats/geoms can be used to visualize distributions and/or estimates. So the "bread-and-butter" data frames in `tidybayes` don't really look like those in `broom`, I think.

To illustrate what I mean, take `broom::tidy` applied to a brms model from [this example](http://mjskay.github.io/tidybayes/articles/tidy-brms.html#ordinal-models) in tidybayes:

```r
> tidy(m_esoph_brm)
            term      estimate std.error        lower        upper
1 b_Intercept[1]   -1.01023155 0.2502050   -1.4266451   -0.6056389
2 b_Intercept[2]    0.22024605 0.2241393   -0.1405996    0.5871785
3 b_Intercept[3]    1.32763067 0.2693483    0.9000693    1.7931983
4      b_agegp.L   -0.39013338 0.5027604   -1.2242937    0.4090304
5      b_agegp.Q   -0.38789888 0.5001648   -1.2081085    0.4192648
6      b_agegp.C   -0.24241699 0.4744691   -1.0293042    0.5243998
7      b_agegpE4    0.02247866 0.4678554   -0.7368510    0.7996794
8      b_agegpE5   -0.03873918 0.4706439   -0.8356114    0.7363095
9           lp__ -134.81997698 2.0283658 -138.5571265 -132.1187481
```

`tidybayes` does not provide a single function that gives an equivalent result, though it can be built up from primitives if desired:

```r
> m_esoph_brm %>% as_sample_tibble() %>% gather_terms() %>% mean_qi()
# A tibble: 9 x 5
# Groups:   term [9]
  term            estimate conf.low conf.high .prob
  <chr>              <dbl>    <dbl>     <dbl> <dbl>
1 b_agegp.C        -0.242    -1.17      0.671  0.95
2 b_agegp.L        -0.390    -1.37      0.565  0.95
3 b_agegp.Q        -0.388    -1.36      0.568  0.95
4 b_agegpE4         0.0225   -0.869     0.941  0.95
5 b_agegpE5        -0.0387   -0.962     0.888  0.95
6 b_Intercept[1]   -1.01     -1.52     -0.523  0.95
7 b_Intercept[2]    0.220    -0.205     0.670  0.95
8 b_Intercept[3]    1.33      0.837     1.88   0.95
9 lp__           -135.     -140.     -132.     0.95
```

If `mean_qi()` were left off, you get a long-format data frame of draws:

```r
> m_esoph_brm %>% as_sample_tibble() %>% gather_terms()
# A tibble: 36,000 x 4
# Groups:   term [9]
   .chain .iteration term           estimate
    <int>      <int> <chr>             <dbl>
 1      1          1 b_Intercept[1]   -1.40 
 2      1          2 b_Intercept[1]   -0.772
 3      1          3 b_Intercept[1]   -0.972
 4      1          4 b_Intercept[1]   -1.10 
 5      1          5 b_Intercept[1]   -1.35 
 6      1          6 b_Intercept[1]   -0.797
 7      1          7 b_Intercept[1]   -0.798
 8      1          8 b_Intercept[1]   -1.26 
 9      1          9 b_Intercept[1]   -0.852
10      1         10 b_Intercept[1]   -1.28 
# ... with 35,990 more rows
```

One place where duplication might happen is if `broom.mixed` starts to go in a parameter-index-munging direction. `tidybayes` has (I think) fairly sophisticated support for this: it can extract indices in coefficients into columns, automatically merge duplicate indices across variables, and convert data types back into their original form. 

A simple example on the above data:

```r
> m_esoph_brm %>% spread_samples(b_Intercept[i]) %>% mean_qi()
# A tibble: 3 x 5
# Groups:   i [3]
      i b_Intercept conf.low conf.high .prob
  <int>       <dbl>    <dbl>     <dbl> <dbl>
1     1      -1.01    -1.52     -0.523  0.95
2     2       0.220   -0.205     0.670  0.95
3     3       1.33     0.837     1.88   0.95
```

It also handles different variables having different indices:

```r
> m_esoph_brm %>% gather_samples(`b_agegp.*`, b_Intercept[i], regex = TRUE) %>% mean_qi()
# A tibble: 8 x 6
# Groups:   term, i [8]
  term            i estimate conf.low conf.high .prob
  <chr>       <int>    <dbl>    <dbl>     <dbl> <dbl>
1 b_agegp.C      NA  -0.242    -1.17      0.671  0.95
2 b_agegp.L      NA  -0.390    -1.37      0.565  0.95
3 b_agegp.Q      NA  -0.388    -1.36      0.568  0.95
4 b_agegpE4      NA   0.0225   -0.869     0.941  0.95
5 b_agegpE5      NA  -0.0387   -0.962     0.888  0.95
6 b_Intercept     1  -1.01     -1.52     -0.523  0.95
7 b_Intercept     2   0.220    -0.205     0.670  0.95
8 b_Intercept     3   1.33      0.837     1.88   0.95
```

Some more sophisticated examples of this (including multiple indices and back-converting indices that were factors) are [here](http://mjskay.github.io/tidybayes/articles/tidybayes.html#extracting-samples-from-a-fit-in-tidy-format-using-spread_samples).

Another place where we might have overlap or want to coordinate is on what to do with prediction functions---there may be some overlap in functions like `broom::augment`, `tidybayes::add_fitted_samples` and `tidybayes::add_predicted_samples`.

Anyway, curious to hear your thoughts, and happy to coordinate. At the very least we should probably coordinate on naming, which is at least starting to happen in that Stan discourse thread (thanks @alexpghayes for reaching out there).

**Comment by alexpghayes** [comment]
Please correct me if you have a different vision @bbolker, but I think the direction of `broom.mixed` is closely related to the overall direction of `broom`. `broom` really only wants to provide three methods for each model class:

- `tidy`: summarizes model component level information in a tibble
- `glance`: summarizes whole model level information in a tibble
- `augment`: summarizes observation level information in a tibble

Even for fairly complex models, these methods pretty much never take more than 500 lines of code.

The issue is that `broom` has grown to encompass a fairly broad range of models, and Dave and I have little to no experience with them. Choosing exactly what constitutes a reasonable summary, or spot checking existing tidiers, has basically grown to be too large a task from a design point of view. We can make sure the code works, but for many of the tidiers contributed via PRs, it's difficult to assess if they make sense.

Our intended solution is to split `broom` into several packages for tidying. `broom` will provide tidiers for the most common tidiers (likely those in base R), and then domain experts will manage domain specific tidying packages. Currently we're working on a spec for all these sub-packages to implement to keep things consistent. A well-written spec is probably a release or two away -- we have to clean up some internals in `broom` first. We'd like all of domain specify packages to eventually live in [tidymodels](https://github.com/tidymodels), so that users can load a bunch of tools all at once with `library(tidymodels)` like they currently can with `library(tidyverse)`.

Mixed models tidiers have long been a bit of a mess in `broom`, and a while back `broom.mixed` forked off to clean up mixed models tidiers since `broom` development basically hit standstill. Personally, I think of `broom.mixed` as a pilot for the "split broom in a domain specific tidying packages" project (@bbolker I'm curious how this lines up with your view of `broom.mixed` -- if this doesn't line up with your vision let's discuss more in tidyverse/broom#329).

This is a long way of saying that I think `broom.mixed` mainly wants to provide tools to work with *model objects*. It seems like `tidybayes` is focused much more on providing tools for working with posterior samples. This seems like the most natural way to split any duplicate responsibilities. Frequentist implementations of mixed models like those in `lme4`, etc, also seem like they belong in `broom.mixed`.

**Comment by bbolker** [comment]
I agree with more or less all of this; it also implies that `broom.mixed` will stay more or less as it is. The main thing I need to look at/think about is whether I can use `tidybayes` as a back-end for the Bayesian stuff; if `tidybayes` already knows how to extract posterior samples from all of the different types of Bayesian mixed models, and if augmenting/tidying (if not glancing) always requires an operation on the posterior samples (e.g. computing mean or median or HPD interval or quantiles or ...), does it make sense to re-use that code? Or is it simpler/safer to keep `broom.mixed` self-contained at the potential cost of some duplication of code and effort?

**Comment by mjskay** [comment]
Good point---code-sharing at the level of extracting samples could save both of us time and help both packages support a wider range of models.

If it helps you assess the potential for code-sharing at that level, the starting point in looking at tidybayes is probably [as_sample_tibble](http://mjskay.github.io/tidybayes/reference/as_sample_tibble.html). 

For `augment`, the closest cousin in `tidybayes` is probably [add_fitted_samples](http://mjskay.github.io/tidybayes/reference/add_predicted_samples.html)---if I understand correctly, `augment` may be similar to applying `add_fitted_samples` to the original data frame and then doing some summarization. Compared to `as_sample_tibble`, `add_fitted_samples` tends to require more work to support a new model type in my experience, which might suggest that could also be a good place to share code and reduce duplicate work (I already see some `MCMCglmm` stuff in `broom.mixed` that I am excited to check out, as I haven't sat down to figure out how to implement `add_fitted_samples` for `MCMCglmm` yet).

**Comment by mjskay** [comment]
Related to that Stan discourse thread, I've started a publicly-editable [Google spreadsheet](https://docs.google.com/spreadsheets/d/1KbkX9j7wgt4QWYQG3welECtA0wT9mJM1dQaZ2qqzCCU/edit#gid=0) in an attempt to more systematically identify how terminology is being used across packages and where it might be able to be made more consistent. I would love any comments you have (also if you could double-check the broom column).

**Comment by mjskay** [comment]
To update this from my end: `tidybayes` is now on CRAN with an updated naming scheme. A description of the changes in the naming scheme is [here](http://mjskay.github.io/tidybayes/reference/tidybayes-deprecated.html#deprecated-arguments-and-column-names) along with a rationale for the new names (at the bottom of that page).

I opted to go for an internally-consistent naming scheme and to gain compatibility with other packages through functions that can be dropped into a tidy pipeline to rename columns, such as `tidybayes::to_broom_names` and `tidybayes::from_broom_names` (see [here](http://mjskay.github.io/tidybayes/reference/tidy-format-translators.html)).

**Comment by alexpghayes** [comment]
Congrats on the release and thanks for the update!

**Comment by bbolker** [comment]
I think this can be closed.  Looking (albeit only briefly) at `tidybayes`, I concur that there's not a whole here that should (or can) be profitably re-used.  It might be nice to mention `tidybayes` *somewhere* in the docs/vignettes/etc. for `broom.mixed` (in the "other packages you might be interested in", along with `emmeans`, `car`, `sjstats`, etc.), but otherwise I think we're done here.
