### ISSUE TITLE
Error using broom::tidy on rxLogisticRegression

### ISSUE THREAD

**Issue by smithochris** [bbolker/broom.mixed#27]
Hi, 

I am trying to use the broom package with some of the revoscaleR packages.  Specifically, I am trying to use broom::tidy with rxLogisticRegression.  When trying to do so, I get the following error messages:

Error in as.data.frame.default(x) : 
  cannot coerce class "c("LogisticRegression", "mlModel")" to a data.frame
Calls: source ... tidy.default -> as.data.frame -> as.data.frame.default
In addition: Warning message:
In tidy.default(logitObj) :
  No method for tidying an S3 object of class LogisticRegression , using as.data.frameNo method for tidying an S3 object of class mlModel , using as.data.frame 

Is there any way to get around this issue? Thanks!

**Comment by bbolker** [comment]
I think this might be in the wrong place ...  

- The `broom.mixed` is specifically for tidiers for hierarchical/multi-level/mixed models. I'm not too familiar with revoscaleR, but as far as I know `rxLogisticRegression` isn't in this category ...
- you might want to post this at the [issues list for the main broom package](https://github.com/tidymodels/broom/issues) ...
- but before that you might want to take a look at the broom document on [adding tidiers](https://broom.tidyverse.org/articles/adding-tidiers.html); `broom` can't automatically handle new packages, someone has to figure out the internal structure of the model objects and write appropriate methods.

good luck ...
