### ISSUE TITLE
CRAN submission soon?

### ISSUE THREAD

**Issue by IndrajeetPatil** [bbolker/broom.mixed#29]
Some of my package functions rely on `broom` tidiers for mixed-effects models and since the last release of `broom` they print warnings about these deprecated functions. This means that all these warnings will also shows up for my `R CMD CHECK` and I'd like to avoid that. So it will be better for me to switch to `broom.mixed` before releasing any new versions on `CRAN`. 

Are there plans to submit `broom.mixed` to `CRAN` any time soon? I'd like to have a rough timeline in mind for my own package releases accordingly. Thanks.

**Comment by bbolker** [comment]
I'm hoping *very* soon.  I submitted a version before the CRAN hiatus, which bounced due to some very small issues; I ran out of momentum resolving these, but have asked CRAN for some clarification and hope to resubmit any day now ...

**Comment by IndrajeetPatil** [comment]
Cool, thanks!

**Comment by bbolker** [comment]
just submitted version 0.2.2, fingers crossed.
