### ISSUE TITLE
`conf.level` not working for merMod objects

### ISSUE THREAD

**Issue by strengejacke** [bbolker/broom.mixed#30]
Argument `conf.level` does not affect the confidence intervals in the output...

``` r
library(lme4)
#> Loading required package: Matrix
library(broom.mixed)

m <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd), cbpp, binomial, nAGQ = 0)

broom.mixed::tidy(m, conf.int = TRUE, conf.level = .95)
#> # A tibble: 5 x 9
#>   effect group term  estimate std.error statistic  p.value conf.low
#>   <chr>  <chr> <chr>    <dbl>     <dbl>     <dbl>    <dbl>    <dbl>
#> 1 fixed  <NA>  (Int~   -1.36      0.228     -5.98  2.26e-9    -1.81
#> 2 fixed  <NA>  peri~   -0.976     0.303     -3.22  1.29e-3    -1.57
#> 3 fixed  <NA>  peri~   -1.11      0.324     -3.43  5.94e-4    -1.75
#> 4 fixed  <NA>  peri~   -1.56      0.424     -3.67  2.38e-4    -2.39
#> 5 ran_p~ herd  sd__~    0.642    NA         NA    NA          NA   
#> # ... with 1 more variable: conf.high <dbl>

broom.mixed::tidy(m, conf.int = TRUE, conf.level = .5)
#> # A tibble: 5 x 9
#>   effect group term  estimate std.error statistic  p.value conf.low
#>   <chr>  <chr> <chr>    <dbl>     <dbl>     <dbl>    <dbl>    <dbl>
#> 1 fixed  <NA>  (Int~   -1.36      0.228     -5.98  2.26e-9    -1.81
#> 2 fixed  <NA>  peri~   -0.976     0.303     -3.22  1.29e-3    -1.57
#> 3 fixed  <NA>  peri~   -1.11      0.324     -3.43  5.94e-4    -1.75
#> 4 fixed  <NA>  peri~   -1.56      0.424     -3.67  2.38e-4    -2.39
#> 5 ran_p~ herd  sd__~    0.642    NA         NA    NA          NA   
#> # ... with 1 more variable: conf.high <dbl>
```

<sup>Created on 2018-10-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bbolker** [comment]
thanks for this and others, will try to get to them all soon ...

**Comment by bbolker** [comment]
should fixed: e9da82039

**Comment by IndrajeetPatil** [comment]
Do you plan to have the next release soon (with all the confidence interval issues raised by @strengejacke fixed)? 

After its release on `CRAN`, I had immediately added `broom.mixed` as a dependency for two of my packages. But now the results from my package functions that rely on `merMod` tidiers look incorrect on `CRAN` and I would like to correct that asap.

**Comment by bbolker** [comment]
Yes.  CRAN wants a new version by October 22 anyway to deal with some dependency issues.  The most critical (IMO) of the issues raised by @strengejacke are addressed - all the ones that I would classify as actual bugs - but I was hoping to close a couple more issues (#34, #37) before sending it ...

**Comment by IndrajeetPatil** [comment]
Cool, sounds good.
