### ISSUE TITLE
release-critical/wishlist for 0.2.3 ?

### ISSUE THREAD

**Issue by bbolker** [bbolker/broom.mixed#38]
CRAN wants a new version by October 22 (the previous version didn't deal properly with making use of Suggested packages conditional, and some of rstanarm/etc. no longer install on r-release ...).

I believe the release-critical issues are dealt with, but anyone who is following the issues could suggest release-critical and/or low-hanging wishlist items.  I've started  a vignette and would like to improve it a bit more before submitting, if possible ...

**Comment by strengejacke** [comment]
- implement HDI for Stan-tidiers

I think this is fairly easy, depending on the method you may want to use to caluclate the HDI. I have implemented a `hdi()` function based on Kruschke's formula. The core code can be found here:
https://github.com/strengejacke/sjstats/blob/2e1747148dfafa2454e12e24c8efc74762c87353/R/HDI.R#L340

I can file a PR if you want.

- Remove `cond`-column if not necessary

This is more a stylistic question, and it depends on your "philosophy" of tidying model summaries. I would suggest to remove the `cond` column from the output if all values are identical (i.e. if there is only a "conditional" model part).

**Comment by bbolker** [comment]
I'll take a look at this. Quick responses:

- there's `coda::HPDinterval()`, which I've used in the past because it's well-established. In fact, it's already in `tidyMCMC` (don't know how long it's been there, or whether it could be made to work easily with stan models)
- the [broom adding-tidiers document](https://cran.r-project.org/web/packages/broom/vignettes/adding-tidiers.html) says
     > It’s better to have a predictable number of columns and unknown number rows than an unknown number of columns and a predictable number of rows.

This might be a different situation, though (since we're not trading off with row predictability ...)

**Comment by strengejacke** [comment]
> * there's `coda::HPDinterval()`, which I've used in the past because it's well-established. In fact, it's already in `tidyMCMC` (don't know how long it's been there, or whether it could be made to work easily with stan models)

ok. I just checked the two functions, and the results are the same. If you use the code I referred to (https://github.com/bbolker/broom.mixed/issues/38#issuecomment-429603410), you may need less code, no transformation (like `as.mcmc()`) and have fewer pkg dependencies.

On the other hand, you have `brms::as.mcmc()` or `rstan::As.mcmc.list()` to convert brmsfit or stanfit objects to an mcmc-object for use with coda.

**Comment by strengejacke** [comment]
Thanks for implementing the HDI-option. I just checked and compared the results to another HDI-function, and the results differ - I'm not sure, why:

``` r
library(rstanarm)
library(sjstats)
library(HDInterval)
library(coda)

fit <- stan_glm(mpg ~ wt + am, data = mtcars, chains = 1)

sjstats::hdi(fit, prob = .9)
#> 
#> # Highest Density Interval
#> 
#>                   HDI(90%)
#>  (Intercept) [31.81 42.04]
#>  wt          [-6.64 -3.95]
#>  am          [-2.35  2.82]
#>  sigma       [ 2.48  3.87]

# results identical, I guess because I use Kruschke's formula 
# to compute the HDI
HDInterval::hdi(as.data.frame(fit), credMass = .9)
#>       (Intercept)        wt        am    sigma
#> lower    31.81405 -6.644528 -2.353877 2.484189
#> upper    42.04488 -3.951020  2.821217 3.869736
#> attr(,"credMass")
#> [1] 0.9

coda::HPDinterval(coda::as.mcmc(as.data.frame(fit)), prob = .9)
#>                 lower     upper
#> (Intercept) 31.814053 42.044882
#> wt          -6.644528 -3.951020
#> am          -2.353877  2.821217
#> sigma        2.484189  3.869736
#> attr(,"Probability")
#> [1] 0.9
```

<sup>Created on 2018-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I'm not sure which of these methods is more precise, but maybe you should add a note on this in the help from `tidy()`?

**Comment by strengejacke** [comment]
ups? Just saw that this was a bad example as all numbers are matching perfectly... d'oh.
I had this problem with the example-model from broom.mixed, I thought. I'll check this out if there's really a difference between these functions.

**Comment by IndrajeetPatil** [comment]
Is `broom.mixed 0.2.3` on its way to `CRAN`?

I am planning to schedule a new release for my package accordingly.

**Comment by bbolker** [comment]
Not yet, but I plan to submit today. I was hoping to resolve #39 but now I think it'll be best to get this release in and wait ...

**Comment by bbolker** [comment]
Version 0.2.3 posted to CRAN, fingers crossed.

**Comment by bbolker** [comment]
0.2.3 accepted by CRAN, I don't see any open sub-issues above.
