### ISSUE TITLE
release-critical/wishlist for 0.2.4?

### ISSUE THREAD

**Issue by bbolker** [bbolker/broom.mixed#61]
As far as I know all of the low-hanging/critical bugs are now fixed.

@IndrajeetPatil, willing to check your packages with the latest versions?

There's still the big list of feature requests for additional tidiers, and old issues with brms/MCMCglmm, but I don't see a reason not to submit now-ish ... ?

**Comment by IndrajeetPatil** [comment]
Thanks for checking, Ben. Running all the checks now. Will get back to you in a few minutes. 

Excited about the new release!

**Comment by IndrajeetPatil** [comment]
I can confirm that both `ggstatsplot` and `groupedstats` look okay with the new changes to `broom.mixed`.

**Comment by bbolker** [comment]
submitted to CRAN, fingers crossed.

**Comment by bbolker** [comment]
On CRAN now (binaries not yet built, but on the way in the next few days).
