### ISSUE TITLE
`gamlss` present in both `broom` and `broom.mixed`

### ISSUE THREAD

**Issue by IndrajeetPatil** [bbolker/broom.mixed#64]
@alexpghayes and @bbolker: 
The development version of `broom` has gotten rid of all the shared S3 methods between these two packages except for one: `gamlss`.

What's the future of this tidier? `broom` or `broom.mixed`?
This is especially important because `broom.mixed` has changed this tidier since it separated from `broom`, while the latter hasn't changed. This means `tidy()` will return results based on whatever method is currently loaded.

**Comment by alexpghayes** [comment]
It makes sense for the `gamlss` and `gam` (and `Gam`) tidiers to stick together. There's also https://github.com/tidymodels/broom/issues/596 discussing how to implement tidiers for GAMMs. I think these tidiers could arguably belong in:

- `broom`
- `broom.mixed`
- `gratia`

**Comment by bbolker** [comment]
I don't have strong feelings.

**Comment by IndrajeetPatil** [comment]
I have opened a PR at `broom` (https://github.com/tidymodels/broom/pull/653) that brings the `gamlss` tidier up to speed with changes made to the same tidier in `broom.mixed`.

**Comment by alexpghayes** [comment]
Let's keep `tidy.gamlss()` in `broom` then. Will merge that in when I get a moment.

**Comment by bbolker** [comment]
https://github.com/tidymodels/broom/issues/507
