### ISSUE TITLE
confidence interval of random effects out of order

### ISSUE THREAD

**Issue by khusmann** [bbolker/broom.mixed#65]
Hello, the confidence intervals seem to be out of order when I run

`tidy(model, conf.int=T, conf.method='profile')`

![image](https://user-images.githubusercontent.com/167160/54243823-5fbc4000-4500-11e9-8ce7-7c5d1550f487.png)

Notice the estimate for sd__occasion is 0.115 but confint is [-.596, -.491], while the estimate for cor__(Intercept).occasion is -.546 with confidence interval [.10, .13]. This looks flipped, probably from the ordering of the output of confint().

Thanks for your work on this! Cheers.

**Comment by bbolker** [comment]
yikes, will take a look.

**Comment by bbolker** [comment]
Hopefully, resolved in 68e494f78 . Can you install dev version and see if it fixes your problem?

**Comment by khusmann** [comment]
Looks good now! Although I sort of miss the SDs and CORs being grouped, because then it sort of matches the order of the fixed effects. (And I see them grouped in this way in papers like https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2975938/pdf/nihms245694.pdf )

Could we maybe add a column, (something like "estimate.type"), which could have values "value", "interaction-2", "interaction-3", etc. (for different orders of interactions), "sd", "corr" so I could sort by this?

On second thought, I guess I could just split based on the __ in the term name. I'm new to this, so I'm not sure what the general population will consider most useful.

Thanks again!

**Comment by bbolker** [comment]
Here's an incantation for sorting in the order you want:
```
        (tt %>% separate(term,c("type","term"),sep="__",fill="left")
            %>% arrange(!is.na(type),desc(type)))
```

I've added this to the examples in the documentation.
(In previous examples the sds were first and the cors last *within each RE term*; this sorting puts *all* the sds first and *all* the cors last ...)

**Comment by khusmann** [comment]
perfect. this is wonderful, thank you for your time!
