### ISSUE TITLE
Error: No tidy method for objects of class summary.glmmTMB

### ISSUE THREAD

**Issue by skanskan** [bbolker/broom.mixed#67]
Hello.
I have installed broom.mixed from cran and when I try to use it with glmmTMB models I get this error:
`tidy(summary(mymodel))`

> Error: No tidy method for objects of class summary.glmmTMB

and the same error for glance.

**Comment by bbolker** [comment]
I think you just want `tidy(mymodel)`, `glance(mymodel)`?  Tidying *sensu* broom doesn't work on summary objects, it works on the model objects themselves ...

**Comment by skanskan** [comment]
OK, thank you.

And how can I convert that output to LaTeX?
