### ISSUE TITLE
Standardized tests for broom.mixed?

### ISSUE THREAD

**Issue by mattfidler** [bbolker/broom.mixed#69]
Are there some standardized tests for broom.mixed objects that you are exporting?

**Comment by bbolker** [comment]
most of the tests are copied (not even inherited!) from `broom`: see `tests/testthat/helper-checkers.R`.  Maybe `broom` has exported some of these?  (They don't live in the package, though -- they live in the package infrastructure.  I don't think the tests get installed with the package, so it might make sense to move these to `inst/` so they could be accessed via `source(system.file("test_helpers","helper-checkers.R", package="broom.mixed"))`

**Comment by mattfidler** [comment]
Thanks for the info.  For me, I just copied your helpers which you copied from broom.
