### ISSUE TITLE
install.package issue

### ISSUE THREAD

**Issue by JeffreyBlumenthal** [bbolker/broom.mixed#78]
>install_github("bbolker/broom.mixed") 
resulted in  error and failure to install. 

> install_github("bbolker/broom.mixed", type ="source") 
worked

**Comment by bbolker** [comment]
Sorry I didn't see/respond this sooner.  Is this still happening? Can you give more details please? (What error message is reported?  What OS are you using?) haven't noticed any problems with `remotes::install_github("bbolker/broom.mixed")` in the past (and seems to work OK at the moment).

**Comment by JeffreyBlumenthal** [comment]
Hi Dr. Bolker,
Actually, we corresponded about this when it was first occurring a few months ago I guess and I followed a different link to the package that worked ... honestly, I don't recall the details but it worked out in the end. I think the OS was Windows 7. Maybe I can find the email and fwd it back to you for your reference.

Many thanks,
Jeff.

________________________________
